export default {
  LOADING_REPOS_SUCCESS: "LOADING_REPOS_SUCCESS",
  LOADING_REPOS_FAIL: "LOADING_REPOS_FAIL",
  HAS_MORE: "HAS_MORE",
  LOAD_REPOS: "LOAD_REPOS",
  LOAD_USER: "LOAD_USER",
  LOADING_USER_SUCCESS: "LOADING_USER_SUCCESS",
};
